# Generated by Django 4.0.5 on 2022-10-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('loundry_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpapp.user')),
            ],
        ),
    ]
