# Generated by Django 4.1.1 on 2022-10-24 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laundry_tag', models.CharField(max_length=255)),
                ('image', models.ImageField(default='static/upload_img/img/image.jpg', upload_to='img/')),
                ('memo', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Cabinets',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='cabinet',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpapp.categories'),
        ),
    ]
