# Generated by Django 4.0.5 on 2022-10-26 05:28
# Generated by Django 4.1.1 on 2022-10-26 01:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0002_cabinet_categories_delete_cabinets_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
