# Generated by Django 4.0.5 on 2022-11-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0003_cabinet_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
