# Generated by Django 4.0.5 on 2022-11-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0004_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
