# Generated by Django 4.0.5 on 2022-12-15 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpapp', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Washer_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_id', to='helpapp.cabinet')),
                ('washer_log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washer_log_id', to='helpapp.washer_log')),
            ],
        ),
    ]
