# Generated by Django 4.0.5 on 2022-12-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0007_alter_cabinet_memo_washer_log_laundry'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='judge_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='washer_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
