# Generated by Django 4.0.5 on 2022-12-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0008_profile_judge_cnt_profile_washer_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
    ]
