# Generated by Django 4.0.5 on 2022-12-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0009_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
