# Generated by Django 4.0.5 on 2022-12-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0009_alter_profile_image'),
        ('helpapp', '0010_alter_report_image'),
    ]

    operations = [
    ]
