# Generated by Django 4.0.5 on 2022-12-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0011_merge_20221222_1544'),
        ('helpapp', '0011_merge_20221222_1548'),
    ]

    operations = [
    ]
