# Generated by Django 4.0.5 on 2023-01-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0012_merge_20221222_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='annotation',
            field=models.BooleanField(default=False),
        ),
    ]
