# Generated by Django 4.0.5 on 2023-01-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0013_report_annotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundry',
            old_name='cabinet_id',
            new_name='cabinet',
        ),
        migrations.RenameField(
            model_name='laundry',
            old_name='washer_log_id',
            new_name='washer_log',
        ),
    ]
