# Generated by Django 4.0.5 on 2023-01-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0014_rename_cabinet_id_laundry_cabinet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='diff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
