# Generated by Django 4.0.5 on 2023-01-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0015_report_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='diff',
        ),
    ]
